# Generated by Django 5.2 on 2025-04-04 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sandwich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SauceQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_sauce', models.BooleanField(default=False)),
                ('sandwich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m2mb.sandwich')),
                ('sauce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m2mb.sauce')),
            ],
        ),
        migrations.AddField(
            model_name='sandwich',
            name='sauces',
            field=models.ManyToManyField(through='m2mb.SauceQuantity', to='m2mb.sauce'),
        ),
    ]
