# Generated by Django 5.2 on 2025-04-04 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m2mb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saucequantity',
            old_name='extra_sauce',
            new_name='grilled',
        ),
    ]
