# Generated by Django 5.2 on 2025-04-04 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m2mb', '0002_rename_extra_sauce_saucequantity_grilled'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SauceQuantity',
            new_name='SauceSandwich',
        ),
    ]
